/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buckets.ui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author mhouse
 */
public class BucketsUI extends javax.swing.JFrame {

    /**
     * Creates new form BucketsUI
     */
    public BucketsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePicker = new javax.swing.JFileChooser();
        Tabs = new javax.swing.JTabbedPane();
        watchTab = new javax.swing.JPanel();
        watchDirectoryInput = new javax.swing.JTextField();
        watchInputLabel = new javax.swing.JLabel();
        watchDirectoryPicker = new javax.swing.JButton();
        watchDirectoryList = new javax.swing.JScrollPane();
        watchAdd = new javax.swing.JButton();
        watchRemove = new javax.swing.JButton();
        rulesTab = new javax.swing.JPanel();
        rulesInputLabel = new javax.swing.JLabel();
        rulesRuleInput = new javax.swing.JTextField();
        rulesAdd = new javax.swing.JButton();
        rulesRemove = new javax.swing.JButton();
        rulesRuleList = new javax.swing.JScrollPane();
        rulesRuleInput1 = new javax.swing.JTextField();

        filePicker.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        watchDirectoryInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchDirectoryInputActionPerformed(evt);
            }
        });

        watchInputLabel.setText("Add/Remove Directory");

        watchDirectoryPicker.setText("...");
        watchDirectoryPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchDirectoryPickerActionPerformed(evt);
            }
        });

        watchDirectoryList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        watchAdd.setText("Add");
        watchAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchAddActionPerformed(evt);
            }
        });

        watchRemove.setText("Remove");
        watchRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout watchTabLayout = new javax.swing.GroupLayout(watchTab);
        watchTab.setLayout(watchTabLayout);
        watchTabLayout.setHorizontalGroup(
            watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(watchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(watchTabLayout.createSequentialGroup()
                        .addComponent(watchInputLabel)
                        .addGap(18, 18, 18)
                        .addComponent(watchDirectoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(watchDirectoryPicker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(watchAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(watchRemove)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(watchDirectoryList, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        watchTabLayout.setVerticalGroup(
            watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(watchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(watchInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchDirectoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchDirectoryPicker)
                    .addComponent(watchAdd)
                    .addComponent(watchRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(watchDirectoryList)
                .addContainerGap())
        );

        Tabs.addTab("Watch", watchTab);

        rulesInputLabel.setText("Add Rule");

        rulesRuleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesRuleInputActionPerformed(evt);
            }
        });

        rulesAdd.setText("Add");
        rulesAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesAddActionPerformed(evt);
            }
        });

        rulesRemove.setText("Remove");
        rulesRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesRemoveActionPerformed(evt);
            }
        });

        rulesRuleList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        rulesRuleInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesRuleInput1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rulesTabLayout = new javax.swing.GroupLayout(rulesTab);
        rulesTab.setLayout(rulesTabLayout);
        rulesTabLayout.setHorizontalGroup(
            rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesTabLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rulesInputLabel)
                .addGap(18, 18, 18)
                .addComponent(rulesRuleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rulesRuleInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rulesAdd)
                .addGap(18, 18, 18)
                .addComponent(rulesRemove)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(rulesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rulesRuleList)
                .addContainerGap())
        );
        rulesTabLayout.setVerticalGroup(
            rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rulesRuleInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rulesRuleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rulesInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rulesAdd)
                    .addComponent(rulesRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rulesRuleList, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabs.addTab("Rules", rulesTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
        );

        Tabs.getAccessibleContext().setAccessibleName("Edit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void watchDirectoryInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchDirectoryInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchDirectoryInputActionPerformed

    private void watchRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchRemoveActionPerformed

    private void watchDirectoryPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchDirectoryPickerActionPerformed
        int result = filePicker.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String file = filePicker.getSelectedFile().getAbsolutePath();
            watchDirectoryInput.setText(file);
        }
    }//GEN-LAST:event_watchDirectoryPickerActionPerformed

    private void watchAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchAddActionPerformed

    private void rulesRuleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesRuleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesRuleInputActionPerformed

    private void rulesAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesAddActionPerformed

    private void rulesRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesRemoveActionPerformed

    private void rulesRuleInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesRuleInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesRuleInput1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BucketsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JFileChooser filePicker;
    private javax.swing.JButton rulesAdd;
    private javax.swing.JLabel rulesInputLabel;
    private javax.swing.JButton rulesRemove;
    private javax.swing.JTextField rulesRuleInput;
    private javax.swing.JTextField rulesRuleInput1;
    private javax.swing.JScrollPane rulesRuleList;
    private javax.swing.JPanel rulesTab;
    private javax.swing.JButton watchAdd;
    private javax.swing.JTextField watchDirectoryInput;
    private javax.swing.JScrollPane watchDirectoryList;
    private javax.swing.JButton watchDirectoryPicker;
    private javax.swing.JLabel watchInputLabel;
    private javax.swing.JButton watchRemove;
    private javax.swing.JPanel watchTab;
    // End of variables declaration//GEN-END:variables
}
