/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buckets.ui;

import buckets.data.events.BucketsEvent;
import buckets.data.events.AddDirectory;
import buckets.data.events.RemoveDirectory;
import buckets.data.events.DirectoryAdded;
import buckets.data.events.AddRule;
import buckets.data.events.RemoveRule;
import buckets.rules.RuleSet;
import buckets.rules.Rule;

import buckets.data.Broadcaster;
import buckets.data.Subscriber;

import javax.swing.JFileChooser;

import java.nio.file.Paths;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.stream.Collectors;

import javax.swing.event.ListSelectionListener;

/**
 *
 * @author mhouse
 */
public class BucketsUI extends javax.swing.JFrame implements Subscriber, ListSelectionListener {
	private final Broadcaster broadcaster;
	
    /**
     * Creates new form BucketsUI
     */
    public BucketsUI(Broadcaster b) {
        initComponents();
        broadcaster = b;
    }
    
    public void initCustom(){
        watchList.addListSelectionListener(this);
    }
    
    public void valueChanged(javax.swing.event.ListSelectionEvent e){
        String selected = watchList.getSelectedValue();
        watchDirectoryInput.setText(selected);
    }
    
    @Override
    public void notify ( BucketsEvent e ) {}
    
    public void setDirectories( ArrayList<Path> paths ){
        watchList.setListData(paths.stream()
            .map(p -> p.toString())
            .toArray(String[]::new));
    }
    
    public void setRules( RuleSet rules ){
        ArrayList<Rule> r = rules.asList();  
        watchList.setListData(r.stream()
            .map(p -> p.toString())
            .toArray(String[]::new));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePicker = new javax.swing.JFileChooser();
        Tabs = new javax.swing.JTabbedPane();
        watchTab = new javax.swing.JPanel();
        watchDirectoryInput = new javax.swing.JTextField();
        watchInputLabel = new javax.swing.JLabel();
        watchDirectoryPicker = new javax.swing.JButton();
        watchDirectoryList = new javax.swing.JScrollPane();
        watchList = new javax.swing.JList<>();
        watchAdd = new javax.swing.JButton();
        watchRemove = new javax.swing.JButton();
        rulesTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        regexEntry = new javax.swing.JTextField();
        moveToEntry = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addRuleBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ruleList = new javax.swing.JList<>();
        removeRuleBtn = new javax.swing.JButton();

        filePicker.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        watchDirectoryInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchDirectoryInputActionPerformed(evt);
            }
        });

        watchInputLabel.setText("Add Directory");

        watchDirectoryPicker.setText("...");
        watchDirectoryPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchDirectoryPickerActionPerformed(evt);
            }
        });

        watchDirectoryList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        watchDirectoryList.setViewportView(watchList);

        watchAdd.setText("Add");
        watchAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchAddActionPerformed(evt);
            }
        });

        watchRemove.setText("Remove");
        watchRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout watchTabLayout = new javax.swing.GroupLayout(watchTab);
        watchTab.setLayout(watchTabLayout);
        watchTabLayout.setHorizontalGroup(
            watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(watchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(watchDirectoryList)
                    .addGroup(watchTabLayout.createSequentialGroup()
                        .addComponent(watchInputLabel)
                        .addGap(18, 18, 18)
                        .addComponent(watchDirectoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(watchDirectoryPicker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(watchAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(watchRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        watchTabLayout.setVerticalGroup(
            watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(watchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(watchInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchDirectoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchDirectoryPicker)
                    .addComponent(watchRemove)
                    .addComponent(watchAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(watchDirectoryList, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabs.addTab("Watch", watchTab);

        jLabel2.setText("Regex");

        jLabel3.setText("Move To");

        regexEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regexEntryActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addRuleBtn.setText("Add");
        addRuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRuleBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("<html>Add a regular expression and a location to move the matching file to.</html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jScrollPane1.setViewportView(ruleList);

        removeRuleBtn.setText("Remove");
        removeRuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRuleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rulesTabLayout = new javax.swing.GroupLayout(rulesTab);
        rulesTab.setLayout(rulesTabLayout);
        rulesTabLayout.setHorizontalGroup(
            rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(rulesTabLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rulesTabLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(regexEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rulesTabLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(moveToEntry)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rulesTabLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addRuleBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeRuleBtn)))))
                .addContainerGap())
        );
        rulesTabLayout.setVerticalGroup(
            rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regexEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(addRuleBtn)
                    .addComponent(removeRuleBtn)
                    .addComponent(moveToEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabs.addTab("Rules", rulesTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
        );

        Tabs.getAccessibleContext().setAccessibleName("Edit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void watchDirectoryInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchDirectoryInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchDirectoryInputActionPerformed

    private void watchRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchRemoveActionPerformed
        RemoveDirectory e = new RemoveDirectory(watchDirectoryInput.getText());
        broadcaster.broadcast(e);
    }//GEN-LAST:event_watchRemoveActionPerformed

    private void watchDirectoryPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchDirectoryPickerActionPerformed
        int result = filePicker.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String file = filePicker.getSelectedFile().getAbsolutePath();
            watchDirectoryInput.setText(file);
        }
    }//GEN-LAST:event_watchDirectoryPickerActionPerformed

    private void watchAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchAddActionPerformed
        AddDirectory e = new AddDirectory(watchDirectoryInput.getText());
        broadcaster.broadcast(e);
    }//GEN-LAST:event_watchAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int result = filePicker.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String file = filePicker.getSelectedFile().getAbsolutePath();
            moveToEntry.setText(file);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regexEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regexEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regexEntryActionPerformed

    private void addRuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRuleBtnActionPerformed
        AddRule e = new AddRule(regexEntry.getText(),moveToEntry.getText());
        broadcaster.broadcast(e);
    }//GEN-LAST:event_addRuleBtnActionPerformed

    private void removeRuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRuleBtnActionPerformed
        RemoveRule e = new RemoveRule(regexEntry.getText(),moveToEntry.getText());
        broadcaster.broadcast(e);
    }//GEN-LAST:event_removeRuleBtnActionPerformed
    
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BucketsUI(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton addRuleBtn;
    private javax.swing.JFileChooser filePicker;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moveToEntry;
    private javax.swing.JTextField regexEntry;
    private javax.swing.JButton removeRuleBtn;
    private javax.swing.JList<String> ruleList;
    private javax.swing.JPanel rulesTab;
    private javax.swing.JButton watchAdd;
    private javax.swing.JTextField watchDirectoryInput;
    private javax.swing.JScrollPane watchDirectoryList;
    private javax.swing.JButton watchDirectoryPicker;
    private javax.swing.JLabel watchInputLabel;
    private javax.swing.JList<String> watchList;
    private javax.swing.JButton watchRemove;
    private javax.swing.JPanel watchTab;
    // End of variables declaration//GEN-END:variables
}
