/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buckets.ui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author mhouse
 */
public class BucketsUI extends javax.swing.JFrame {

    /**
     * Creates new form BucketsUI
     */
    public BucketsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePicker = new javax.swing.JFileChooser();
        Tabs = new javax.swing.JTabbedPane();
        watchTab = new javax.swing.JPanel();
        watchDirectoryInput = new javax.swing.JTextField();
        watchInputLabel = new javax.swing.JLabel();
        watchDirectoryPicker = new javax.swing.JButton();
        watchDirectoryList = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        watchAdd = new javax.swing.JButton();
        watchRemove = new javax.swing.JButton();
        rulesTab = new javax.swing.JPanel();

        filePicker.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        watchDirectoryInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchDirectoryInputActionPerformed(evt);
            }
        });

        watchInputLabel.setText("Add/Remove Directory");

        watchDirectoryPicker.setText("...");
        watchDirectoryPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchDirectoryPickerActionPerformed(evt);
            }
        });

        watchDirectoryList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel1.setText("none");

        jButton1.setForeground(new java.awt.Color(211, 47, 47));
        jButton1.setText("Remove");
        jButton1.setToolTipText("remove directory");
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMinimumSize(new java.awt.Dimension(11, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        watchDirectoryList.setViewportView(jPanel1);

        watchAdd.setText("Add");
        watchAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchAddActionPerformed(evt);
            }
        });

        watchRemove.setText("Remove");
        watchRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout watchTabLayout = new javax.swing.GroupLayout(watchTab);
        watchTab.setLayout(watchTabLayout);
        watchTabLayout.setHorizontalGroup(
            watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(watchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(watchTabLayout.createSequentialGroup()
                        .addComponent(watchInputLabel)
                        .addGap(18, 18, 18)
                        .addComponent(watchDirectoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(watchDirectoryPicker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(watchAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(watchRemove)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(watchDirectoryList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        watchTabLayout.setVerticalGroup(
            watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(watchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(watchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(watchInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchDirectoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchDirectoryPicker)
                    .addComponent(watchAdd)
                    .addComponent(watchRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(watchDirectoryList)
                .addContainerGap())
        );

        Tabs.addTab("Watch", watchTab);

        javax.swing.GroupLayout rulesTabLayout = new javax.swing.GroupLayout(rulesTab);
        rulesTab.setLayout(rulesTabLayout);
        rulesTabLayout.setHorizontalGroup(
            rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        rulesTabLayout.setVerticalGroup(
            rulesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        Tabs.addTab("Rules", rulesTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
        );

        Tabs.getAccessibleContext().setAccessibleName("Edit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void watchDirectoryInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchDirectoryInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchDirectoryInputActionPerformed

    private void watchRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchRemoveActionPerformed

    private void watchDirectoryPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchDirectoryPickerActionPerformed
        int result = filePicker.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String file = filePicker.getSelectedFile().getAbsolutePath();
            watchDirectoryInput.setText(file);
        }
    }//GEN-LAST:event_watchDirectoryPickerActionPerformed

    private void watchAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watchAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BucketsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BucketsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JFileChooser filePicker;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel rulesTab;
    private javax.swing.JButton watchAdd;
    private javax.swing.JTextField watchDirectoryInput;
    private javax.swing.JScrollPane watchDirectoryList;
    private javax.swing.JButton watchDirectoryPicker;
    private javax.swing.JLabel watchInputLabel;
    private javax.swing.JButton watchRemove;
    private javax.swing.JPanel watchTab;
    // End of variables declaration//GEN-END:variables
}
